CREATE DATABASE SUCOS_VENDAS;

USE SUCOS_VENDAS;


CREATE TABLE [TABELA DE CLIENTES]
(
	[CPF] [VARCHAR](11),
	[NOME] [VARCHAR](100),
	[ENDERECO 1] [VARCHAR] (150),
	[ENDERECO 2] [VARCHAR] (150),
	[BAIRRO] [VARCHAR] (50),
	[CIDADE] [VARCHAR] (50),
	[ESTADO] [VARCHAR] (2),
	[CEP] [VARCHAR] (8),
	[DATA DE NASCIMENTO] [DATE],
	[IDADE] [SMALLINT],
	[SEXO] [VARCHAR] (1),
	[LIMITE DE CREDITO] [MONEY],
	[VOLUME DE COMPRA] [FLOAT],
	[PRIMEIRA COMPRA] [BIT]
)

CREATE TABLE [dbo].[TABELA DE PRODUTOS](
	[CODIGO DO PRODUTO] [varchar](10) NULL,
	[NOME DO PRODUTO] [varchar](50) NULL,
	[EMBALAGEM] [varchar](20) NULL,
	[TAMANHO] [varchar](10) NULL,
	[SABOR] [varchar](20) NULL,
	[PREÇO DE LISTA] [smallmoney] NULL
) ON [PRIMARY]

CREATE TABLE [TABELA DE VENDEDORES](
	[MATRICULA] [varchar](5),
	[NOME] [varchar](100),
	[PERCENTUAL COMISSAO] [float]
)

DROP TABLE [TABELA DE CLIENTES]

INSERT INTO [TABELA DE PRODUTOS]
([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PREÇO DE LISTA])
VALUES 
('1040107', 'Light - 350 ml - Melância', 'Lata', '350 ml', 'Melância', 4.56)

INSERT INTO [TABELA DE PRODUTOS]
([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PREÇO DE LISTA])
VALUES 
('1037797', 'Clean - 2 Litros - Laranja', 'PET', '2 L', 'Laranja', 16.01)

INSERT INTO [TABELA DE PRODUTOS]
([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PREÇO DE LISTA])
VALUES 
('1000889', 'Sabor da Motanha - 700 ml - Uva', 'Garrafa', '700 ml', 'Uva', 6.31)


INSERT INTO [TABELA DE VENDEDORES]
([MATRICULA], [NOME], [PERCENTUAL COMISSAO])
VALUES
('00233', 'José Geraldo da Fonseca', 0.10)

INSERT INTO [TABELA DE VENDEDORES]
([MATRICULA], [NOME], [PERCENTUAL COMISSAO])
VALUES
('00235', 'Márcio Almeida Silva', 0.08)

INSERT INTO [TABELA DE VENDEDORES]
([MATRICULA], [NOME], [PERCENTUAL COMISSAO])
VALUES
('00236', 'Cláudia Morais', 0.08)